### ISSUE TITLE
center_ops_cuda

### ISSUE THREAD

**Issue by xhjiang-pixel** [ocNflag/point2seq#1]
Hi, ocNflag. Thanks for your works.  I was training the code and there was an ImportError:  cannot import name 'center_ops_cuda' from 'pcdet.ops.center_ops' (unknown location). I wonder if there was something I missed.

**Comment by ocNflag** [comment]
check ur setup stage, especially the compilation stage, to see if there are any errors or warning information. I am currently under quarantine and may not be able to modify the code for several weeks.

**Comment by ocNflag** [comment]
Check your setup stage, especially the compilation stage, to see if there are any errors or warning information. I am currently under quarantine and may not be able to reply in time or modify the code for several weeks.
